### ISSUE TITLE
fatfs/drivers/fatfs_sd.c cannot be compiled with GCC 7.3.1

### ISSUE THREAD

**Issue by alpo** [MaJerle/stm32fxxx_hal_libraries#32]
Using gcc version 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] (GNU Tools for Arm Embedded Processors 7-2018-q3-update) 
I'm getting the error 
`fatfs/drivers/fatfs_sd.c:158:12: error: conflicting types for 'select'

/usr/arm-none-eabi/include/sys/select.h:62:5: note: previous declaration of 'select' was here
 int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,`
Shouldn't the use of system function names be considered as bad practice and exterminated?

**Comment by MaJerle** [comment]
@alpo yes, could be. Could you do please a pull request with valid change?
